load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "loggingTest_header",
    hdrs = [
        "LoggingTest.h",
        "LoggingTest.h.in",
    ],
    includes = [
        ".",
    ],
    deps = [
        "//:Logging",
    ],
)
